# Generated by Django 6.0.7 on 2026-07-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='order',
        ),
    ]
